export const white = '#fff'
export const black = '#000'

export const gray = '#343433'
export const beige = '#FDE9D5'
export const yellow = '#FFBA2A'
export const red = '#F85E46'
export const blue = '#80ADE0'
export const pink = '#F89ABF'

export type Theme = 'gray' | 'beige' | 'yellow' | 'red' | 'blue' | 'pink'
export type Typo = 'black' | 'beige' | 'gray' | 'yellow' | 'red'
export type Button = 'yellow' | 'blue'
export type IconColor = 'yellow' | 'gray'
export type IconBackground = 'yellow' | 'blue' | 'red' | 'gray'
